name: Maven CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        maven-version: '3.9.6'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn install
